baseURL: "https://akilan.io/"
title: Akilan
theme: ["PaperMod"]

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: false
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Akilan
    description: "Akilan the not boring developer"
    keywords: [Blog, Portfolio, Akilan]
    author: ["Me","Not boring developer","Akilan Selvacoumar"]
    # author: ["Me", "You"] # multiple authors
   #  images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "2006-02-01"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: The Not Boring Developer
        subtitle: "Akilan Selvacoumar"
        imageUrl: "https://avatars.githubusercontent.com/u/31743758?v=4"
        imageWidth: 160
        imageHeight: 160
        imageTitle: my image
    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to my blog

    socialIcons:
        - name: youtube
          url: "https://www.youtube.com/channel/UChy18QB1hBzZ7MniIW_FJvQ"
        - name: github
          url: "https://github.com/Akilan1999"
        - name: email
          url: "mailto:me@akilan.io"


    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/Akilan1999/Akilan-website/tree/master/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: About
          name: About
          url: /about/
          weight: 10
        - identifier: Resumé
          name: Resumé
          url: /resume/
          weight: 20
        - identifier: Projects
          name: Projects
          url: /projects/
          weight: 30
        - identifier: Technical Posts
          name: Technical Posts
          url: /technicalposts/
          weight: 40
        - identifier: General Posts
          name: General Posts
          url: /Generalposts/
          weight: 50
        - identifier: Papers
          name: Papers
          url: /Papers/
          weight: 50
        - identifier: Chat
          name: Chat
          url: /Chat/
          weight: 60
        - identifier: Hiking
          name: Hiking
          url: /hiking/
          weight: 60
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
